[font]
size = 10

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B "
key = "Space"
mods = "Alt"

[mouse]
hide_when_typing = true

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
startup_mode = "Fullscreen"
