window:
  startup_mode: SimpleFullscreen
font:
  size: 11
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
mouse:
  hide_when_typing: true
key_bindings:
  - key: C
    mods: Command
    action: Copy
  - key: H
    mods: Command
    action: None
  - key: V
    mods: Command
    action: Paste
  - key: Space
    mods: Control
    chars: "\x00"
  - key: Space
    mods: Alt
    chars: "\x1b "
shell:
  program: /bin/zsh
  args:
    - -l
