box: ubuntu

command-timeout: 60

build:
  steps:
      - script:
          name: Initialize locale
          code: |
            apt -y update --fix-missing
            apt -y install locales
            locale-gen en_US.UTF-8

      - script:
          name: Update PPA
          code: |
            apt -y update --fix-missing
            apt -y install software-properties-common
            apt-add-repository -y ppa:martin-frost/thoughtbot-rcm

      - script:
          name: Install Dependencies
          code: |
            apt -y update --fix-missing
            apt -y upgrade
            apt -y install build-essential clang curl git libcairo-dev libcurl4-openssl-dev libdbus-1-dev libgdk-pixbuf2.0-dev libx11-dev rcm ruby sudo zlib1g zlib1g-dev

      - script:
          name: Create user
          code: useradd -m tester

      - script:
          name: Initialize dotfiles
          code: su tester -c 'cp -r /pipeline/source /home/tester/.dotfiles && rcup -f'

      - script:
          name: Update homebrew
          code: su tester -c '. ~/.profile && update homebrew'

      - script:
          name: Update all
          code: su tester -c '. ~/.profile && update dotfiles -bg'
