box: ubuntu

command-timeout: 60
no-response-timeout: 15

build:
  steps:
    - script:
        name: Initialize locale
        code: |
          apt -y update --fix-missing
          apt -y install locales
          locale-gen en_US.UTF-8

    - script:
        name: Update PPA
        code: |
          apt -y update --fix-missing
          apt -y install software-properties-common
          apt-add-repository -y ppa:martin-frost/thoughtbot-rcm

    - script:
        name: Install Dependencies
        code: |
          apt -y update --fix-missing
          apt -y upgrade
          apt -y install build-essential clang curl git libcurl4-openssl-dev libltdl-dev rcm ruby sudo zlib1g-dev

    - script:
        name: Create user
        code: useradd -m tester

    - script:
        name: Initialize dotfiles
        code: |
          su tester -c 'cp -r /pipeline/source /home/tester/.dotfiles && rcup -f'
          rm /home/tester/.gitconfig

    - script:
        name: Update homebrew
        code: su tester -lc 'update homebrew'

    - script:
        name: Update all
        code: su tester -lc 'update all -b'

    - script:
        name: Rerun
        code: su tester -lc 'update all -b'
