version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
        environment:
          TERM: xterm-256color
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pacman -Syu --noconfirm base-devel clang git libnsl
            locale-gen
      - run:
          name: Set up user
          command: |
            useradd -m tester
            cp -r . /home/tester/.dotfiles
            chown -R tester /home/tester/.dotfiles
      - run:
          name: Update Homebrew
          working_directory: /home/tester
          command: |
            su tester -c '. ~/.dotfiles/profile && ~/.dotfiles/local/bin/update-homebrew'
            su tester -c '. ~/.dotfiles/profile && rcup -f'
      - run:
          name: Update all
          working_directory: /home/tester
          command: su tester -c '. ~/.profile && update all -b'
