version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt -y update --fix-missing
            apt -y upgrade
            apt -y install build-essential curl git
      - run:
          name: Create user
          command: useradd -m tester
      - run:
          name: Copy dotfiles
          command: |
            cp -r . /home/tester/.dotfiles
            chown -R tester /home/tester/.dotfiles
      - run:
          name: Update Homebrew
          working_directory: /home/tester
          command: |
            su tester -c '. ~/.dotfiles/profile && ~/.dotfiles/local/bin/update-homebrew'
            su tester -c '. ~/.dotfiles/profile && rcup -f'
      - run:
          name: Update all
          working_directory: /home/tester
          command: su tester -c '. ~/.profile && update all -b'
