name: main
on:
  - push
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@main
      - run: cp -r . ~/.dotfiles
      - run: cp ~/.dotfiles/profile ~/.profile
      - run: update-homebrew
      - run: rcup -f
      - run: update
