name: main
on:
  - push
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: sh -ec "if [ -r ~/.profile ]; then . ~/.profile; fi && . {0}"
    steps:
      - uses: actions/checkout@v4
      - run: cp profile ~/.profile
      - run: cp -r . ~/.dotfiles
      - run: ~/.dotfiles/local/bin/update-homebrew
      - run: rcup -f
      - run: update
