name: main
on:
  - push
jobs:
  main:
    strategy
      matrix: 
        os: 
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: sh -ec ". ~/.profile && . {0}"
    steps:
      - uses: actions/checkout@main
      - run: cp profile ~/.profile
      - run: cp -r . ~/.dotfiles
      - run: ~/.dotfiles/local/bin/update-homebrew
      - run: rcup -f
      - run: update
