name: main
on:
  - push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: cp -r . ~/.dotfiles
      - run: cp ~/.dotfiles/profile ~/.profile
      - run: update-homebrew
        shell: sh -el {0}
      - run: rcup -f
        shell: sh -el {0}
      - run: update
        shell: sh -el {0}
