name: main
on:
  - push
jobs:
  main:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: sh -ec ". ~/.profile && . {0}"
    steps:
      - uses: actions/checkout@main
      - run: sudo apt -y update --fix-missing
      - run: sudo apt install -y openssl
      - run: cp profile ~/.profile
      - run: cp -r . ~/.dotfiles
      - run: ~/.dotfiles/local/bin/update-homebrew
      - run: rcup -f
      - run: update
