name: main
on:
  - push
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh -ec ". ~/.profile && . {0}"
    steps:
      - uses: actions/checkout@main
      - run: cp profile ~/.profile
      - run: cp -r . ~/.dotfiles
      - run: ~/.dotfiles/local/bin/update-homebrew
      - run: rcup -f
      - run: update -s go
      - run: update go
        continue-on-error: true
