name: main
on:
  - push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: sh -ec "if [ -r ~/.profile ]; then . ~/.profile; fi && . {0}"
    steps:
      - uses: actions/checkout@v4
      - run: cp profile ~/.profile
      - run: cp -r . ~/.dotfiles
      - run: ~/.dotfiles/local/bin/update-homebrew
      - run: brew cleanup -s --prune all
      - run: rcup -f
      - run: update
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v3
