name: test
on:
  - push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: sh -ec "if [ -r ~/.profile ]; then . ~/.profile; fi && . {0}"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: |
          sudo apt -y remove firefox google-* llvm* microsoft-* php*
          sudo apt -y autoremove
          sudo apt -y clean
          sudo rm -rf /usr/local/lib/android
        if: runner.os == 'Linux'
      - run: cp profile ~/.profile
      - run: cp -r . ~/.dotfiles
      - run: ~/.dotfiles/local/bin/update-homebrew
      - run: rcup -f
      - run: update
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
