name: test
on:
  - push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: sh -ec "if [ -r ~/.profile ]; then . ~/.profile; fi && . {0}"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: |
          sudo apt -y remove firefox google-* llvm* microsoft-* php*
          sudo apt -y autoremove
          sudo apt -y clean
          sudo rm -rf /usr/local/lib/android
        if: runner.os == 'Linux'
      - run: cp profile ~/.profile
      - run: cp -r . ~/.dotfiles
      - run: ~/.dotfiles/local/bin/update-homebrew
      - run: rcup -f
      - run: update
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: streetsidesoftware/cspell-action@d5d910b521ad408f1e7383c24609079f5a88bdca # v8.2.0
